spring:
  application:
    name: springRestJPA
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mysql
    username: root
    password: root
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    