spring:
  application:
    name: configServer
  cloud:    config:      server:        git:          uri:  C:\Users\aula3m.DESKTOP-3HCU5LN\config-server-repo-peliculas
server:
  port: 8817
  